name: Linter
on: [pull_request]

jobs:
  go-linters:
    name: Go linters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Check code formatting, complexity, style, performance and patterns
        uses: golangci/golangci-lint-action@v3
        with:
          # https://golangci-lint.run/usage/linters/
          args: |
            --disable-all --enable goimports --enable funlen \
             --enable gocyclo --enable errcheck --enable unused \
             --enable staticcheck --enable dupl --enable revive \
             --enable whitespace --enable maligned --enable prealloc

